In [1]:
%load_ext autotime

time: 0 ns (started: 2021-06-19 19:49:38 +05:30)


In [2]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
from skimage.io import imread
from skimage.transform import resize

time: 6.38 s (started: 2021-06-19 19:49:39 +05:30)


In [3]:
data_dir = 'D:/Downloads/Img_Rcg_Data'

time: 0 ns (started: 2021-06-19 19:49:45 +05:30)


In [4]:
ctgs = ['with_mask' , 'without_mask']

time: 0 ns (started: 2021-06-19 19:49:46 +05:30)


In [5]:
flat_data = []
imgs = []
target = []

time: 0 ns (started: 2021-06-19 19:49:47 +05:30)


In [6]:
for i in ctgs:
    img_cls = ctgs.index(i)
    path = os.path.join(data_dir, i)
    for img in os.listdir(path):
        img_array = imread(os.path.join(path,img))
        img_resize = resize(img_array , (150,150,3))
        target.append(img_cls)
        flat_data.append(img_resize.flatten())
        imgs.append(img_resize)

time: 4.69 s (started: 2021-06-19 19:49:48 +05:30)


In [7]:
flat_data

[array([0.19934641, 0.22777778, 0.12189542, ..., 0.0745098 , 0.04313725,
        0.04313725]),
 array([0.42693333, 0.20732549, 0.02877386, ..., 0.80020392, 0.6476549 ,
        0.38555817]),
 array([0.08506928, 0.07722614, 0.08899085, ..., 0.26459346, 0.12854902,
        0.05735163]),
 array([0.1254902 , 0.08627451, 0.05098039, ..., 0.53985621, 0.54890044,
        0.57635142]),
 array([0.0890658 , 0.06945795, 0.09298736, ..., 0.26562092, 0.10705882,
        0.15019608]),
 array([0.88627451, 0.84705882, 0.89019608, ..., 0.20392157, 0.19607843,
        0.2       ]),
 array([0.27636026, 0.24498771, 0.28812497, ..., 0.21961847, 0.16471651,
        0.21569691]),
 array([0.70947712, 0.63888889, 0.55261438, ..., 0.7689281 , 0.74117647,
        0.63155495]),
 array([0.42745176, 0.53343843, 0.40392235, ..., 0.57928157, 0.66163451,
        0.66555608]),
 array([0.15197386, 0.10813072, 0.13456209, ..., 0.79244444, 0.72941176,
        0.77095425]),
 array([0.69093987, 0.67133203, 0.6870183 , ..., 0

time: 32 ms (started: 2021-06-19 19:49:57 +05:30)


In [8]:
target = np.array(target)

time: 0 ns (started: 2021-06-19 19:49:58 +05:30)


In [9]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

time: 15 ms (started: 2021-06-19 19:49:59 +05:30)


In [10]:
target.shape

(204,)

time: 0 ns (started: 2021-06-19 19:49:59 +05:30)


In [11]:
np.unique(target , return_counts = True)

(array([0, 1]), array([102, 102], dtype=int64))

time: 0 ns (started: 2021-06-19 19:50:00 +05:30)


In [12]:
from sklearn.model_selection import train_test_split

time: 437 ms (started: 2021-06-19 19:50:01 +05:30)


In [13]:
X_train , X_test , y_train , y_test = train_test_split(flat_data , target , test_size = 0.2  , random_state = 0)

time: 0 ns (started: 2021-06-19 19:50:02 +05:30)


### USING SVC

In [14]:
from sklearn.svm import SVC

time: 218 ms (started: 2021-06-19 19:50:02 +05:30)


In [15]:
from sklearn.model_selection import GridSearchCV

time: 0 ns (started: 2021-06-19 19:50:05 +05:30)


In [17]:
params = [{'C': (1,10,100,500,1000) } ,
          {'C': (1,10,100,500,1000) , 'gamma':(0.001,0.01,0.1,0.5,1)}]

time: 0 ns (started: 2021-06-19 19:50:24 +05:30)


In [18]:
clf = SVC(probability = True)


time: 0 ns (started: 2021-06-19 19:50:25 +05:30)


In [19]:
clf_grid = GridSearchCV(clf , params , n_jobs = -1, cv = 3 , verbose = 1, scoring = "accuracy")

time: 0 ns (started: 2021-06-19 19:50:28 +05:30)


In [20]:
clf_grid.fit(X_train , y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits


GridSearchCV(cv=3, estimator=SVC(probability=True), n_jobs=-1,
             param_grid=[{'C': (1, 10, 100, 500, 1000)},
                         {'C': (1, 10, 100, 500, 1000),
                          'gamma': (0.001, 0.01, 0.1, 0.5, 1)}],
             scoring='accuracy', verbose=1)

time: 5min 2s (started: 2021-06-19 19:50:29 +05:30)


In [21]:
clf_grid.best_params_

{'C': 1}

time: 16 ms (started: 2021-06-19 19:55:39 +05:30)


In [22]:
clfb = clf_grid.best_estimator_

time: 0 ns (started: 2021-06-19 19:55:40 +05:30)


In [23]:
clfb.predict(X_test)

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1])

time: 453 ms (started: 2021-06-19 19:55:41 +05:30)


In [24]:
from sklearn.metrics import accuracy_score

time: 0 ns (started: 2021-06-19 19:55:44 +05:30)


In [25]:
accuracy_score(y_test , clfb.predict(X_test))

0.975609756097561

time: 468 ms (started: 2021-06-19 19:55:45 +05:30)


### USING KNN

In [35]:
from sklearn.neighbors import KNeighborsClassifier

time: 172 ms (started: 2021-06-19 19:57:10 +05:30)


In [37]:
params = [{'n_neighbors' : np.arange(1, 25)}]

time: 0 ns (started: 2021-06-19 19:57:18 +05:30)


In [38]:
neigh = KNeighborsClassifier()

time: 0 ns (started: 2021-06-19 19:57:20 +05:30)


In [39]:
clf_grid = GridSearchCV(neigh , params , cv = 5 , 
                        scoring = "accuracy")

time: 0 ns (started: 2021-06-19 19:57:21 +05:30)


In [40]:
clf_grid.fit(X_train , y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])}],
             scoring='accuracy')

time: 11.1 s (started: 2021-06-19 19:57:22 +05:30)


In [41]:
clf_grid.best_params_

{'n_neighbors': 4}

time: 0 ns (started: 2021-06-19 19:57:39 +05:30)


In [42]:
clfn = clf_grid.best_estimator_

time: 0 ns (started: 2021-06-19 19:57:40 +05:30)


In [43]:
clfn.predict(X_test)

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1])

time: 63 ms (started: 2021-06-19 19:57:42 +05:30)


In [44]:
accuracy_score(y_test , clfn.predict(X_test))

0.9512195121951219

time: 62 ms (started: 2021-06-19 19:57:44 +05:30)


### USING XGBOOST

In [45]:
from xgboost import XGBClassifier

time: 328 ms (started: 2021-06-19 19:57:49 +05:30)


In [46]:
xgb = XGBClassifier( max_depth = 8, n_estimators = 1000, learning_rate = 0.05, n_jobs = -1)

time: 0 ns (started: 2021-06-19 19:57:50 +05:30)


In [47]:
X_train = np.array(X_train)

time: 47 ms (started: 2021-06-19 19:57:55 +05:30)


In [48]:
y_train = np.array(y_train)

time: 0 ns (started: 2021-06-19 19:57:55 +05:30)


In [49]:
X_test = np.array(X_test)
y_test = np.array(y_test)

time: 16 ms (started: 2021-06-19 19:57:56 +05:30)


In [50]:
xgb.fit(X_train , y_train, early_stopping_rounds=5 , eval_set=[(X_test, y_test)])

c:\users\anive\appdata\local\programs\python\python39\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[19:57:59] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[0]	validation_0-logloss:0.65918
[1]	validation_0-logloss:0.62511
[2]	validation_0-logloss:0.60258
[3]	validation_0-logloss:0.57403
[4]	validation_0-logloss:0.55061
[5]	validation_0-logloss:0.52662
[6]	validation_0-logloss:0.50464
[7]	validation_0-logloss:0.48917
[8]	validation_0-logloss:0.47019
[9]	validation_0-logloss:0.45858
[10]	validation_0-logloss:0.44448
[11]	validation_0-logloss:0.43333
[12]	validation_0-logloss:0.41898
[13]	validation_0-logloss:0.40573
[14]	validation_0-logloss:0.39349
[15]	validation_0-logloss:0.38426
[16]	validation_0-logloss:0.37479
[17]	validation_0-logloss:0.36885
[18]	validation_0-logloss:0.36229
[19]	validation_0-logloss:0.35384
[20]	validation_0-lo

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.05, max_delta_step=0, max_depth=8,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=1000, n_jobs=-1, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

time: 29.1 s (started: 2021-06-19 19:57:58 +05:30)


In [51]:
accuracy_score(y_test , xgb.predict(X_test))

0.926829268292683

time: 188 ms (started: 2021-06-19 19:58:32 +05:30)


### USING NAIVE BAYES

In [52]:
from sklearn.naive_bayes import GaussianNB

time: 16 ms (started: 2021-06-19 19:58:40 +05:30)


In [56]:
clf_NB = GaussianNB()

time: 0 ns (started: 2021-06-19 20:00:33 +05:30)


In [58]:
flat_data = []
imgs = []
target = []

time: 0 ns (started: 2021-06-19 20:00:40 +05:30)


In [59]:
for i in ctgs:
    img_cls = ctgs.index(i)
    path = os.path.join(data_dir, i)
    for img in os.listdir(path):
        img_array = imread(os.path.join(path,img))
        img_resize = resize(img_array , (150,150,3))
        target.append(img_cls)
        flat_data.append(img_resize.flatten())
        imgs.append(img_resize)

time: 1.78 s (started: 2021-06-19 20:00:50 +05:30)


In [60]:
target = np.array(target)

time: 0 ns (started: 2021-06-19 20:01:04 +05:30)


In [61]:
X_train , X_test , y_train , y_test = train_test_split(flat_data , target , test_size = 0.2  , random_state = 0)

time: 16 ms (started: 2021-06-19 20:01:26 +05:30)


In [62]:
clf_NB.fit(X_train , y_train)

GaussianNB()

time: 281 ms (started: 2021-06-19 20:01:46 +05:30)


In [63]:
accuracy_score(y_test , clf_NB.predict(X_test))

0.926829268292683

time: 109 ms (started: 2021-06-19 20:01:59 +05:30)


### DecisionTreeClassifier

In [64]:
from sklearn import tree

time: 140 ms (started: 2021-06-19 20:02:34 +05:30)


In [65]:
clftree = tree.DecisionTreeClassifier()

time: 0 ns (started: 2021-06-19 20:02:43 +05:30)


In [66]:
params_grid = {"max_depth" : [4,5,6,7,8,],
              "min_samples_leaf" : [2,3,10,20,50]}

time: 0 ns (started: 2021-06-19 20:02:57 +05:30)


In [67]:
grid_search = GridSearchCV(clftree, params_grid,n_jobs = -1, cv=5, scoring = 'accuracy')

time: 0 ns (started: 2021-06-19 20:03:08 +05:30)


In [68]:
grid_search.fit(X_train , y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'max_depth': [4, 5, 6, 7, 8],
                         'min_samples_leaf': [2, 3, 10, 20, 50]},
             scoring='accuracy')

time: 1min 21s (started: 2021-06-19 20:03:14 +05:30)


In [69]:
grid_search.best_params_

{'max_depth': 7, 'min_samples_leaf': 20}

time: 0 ns (started: 2021-06-19 20:04:43 +05:30)


In [70]:
cvdt_clf = grid_search.best_estimator_

time: 0 ns (started: 2021-06-19 20:04:52 +05:30)


In [71]:
accuracy_score(y_test, cvdt_clf.predict(X_test))

0.9024390243902439

time: 31 ms (started: 2021-06-19 20:04:58 +05:30)


### RandomForest

In [72]:
from sklearn.ensemble import RandomForestClassifier

time: 47 ms (started: 2021-06-19 20:05:45 +05:30)


In [73]:
rf_clf = RandomForestClassifier(n_estimators = 250, random_state= 0)

time: 0 ns (started: 2021-06-19 20:05:54 +05:30)


In [74]:
params_grid = {"max_features" : [4,5,6,7,8,9,10],
              "min_samples_split" : [2,3,10]}

time: 0 ns (started: 2021-06-19 20:06:02 +05:30)


In [75]:
grid_search = GridSearchCV(rf_clf, params_grid,n_jobs = -1, cv=5, scoring = 'accuracy')

time: 0 ns (started: 2021-06-19 20:06:11 +05:30)


In [76]:
grid_search.fit( X_train, y_train)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(n_estimators=250, random_state=0),
             n_jobs=-1,
             param_grid={'max_features': [4, 5, 6, 7, 8, 9, 10],
                         'min_samples_split': [2, 3, 10]},
             scoring='accuracy')

time: 53.8 s (started: 2021-06-19 20:06:18 +05:30)


In [77]:
grid_search.best_params_

{'max_features': 5, 'min_samples_split': 3}

time: 0 ns (started: 2021-06-19 20:12:19 +05:30)


In [78]:
cvrf_clf = grid_search.best_estimator_

time: 0 ns (started: 2021-06-19 20:12:26 +05:30)


In [79]:
accuracy_score(y_test, cvrf_clf.predict(X_test))

0.975609756097561

time: 47 ms (started: 2021-06-19 20:12:32 +05:30)


### Logistic Regression

In [80]:
from sklearn.linear_model import LogisticRegression

time: 0 ns (started: 2021-06-19 20:29:06 +05:30)


In [81]:
lr = LogisticRegression()

time: 0 ns (started: 2021-06-19 20:29:31 +05:30)


In [82]:
lr.fit(X_train , y_train)

c:\users\anive\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

time: 2.44 s (started: 2021-06-19 20:29:56 +05:30)


In [83]:
accuracy_score(y_test , lr.predict(X_test))

0.9024390243902439

time: 31 ms (started: 2021-06-19 20:30:43 +05:30)
